from django.urls import include, path, re_path
from django.contrib.auth import views as auth_views
from cvdp import views
from cvdp.groups import views as groupviews
from cvdp.cases import views as caseviews
from cvdp.messages import views as msgviews
from cvdp.manage import views as manageviews
from cvdp.tickets import views as ticketviews
from cvdp.report import views as reportviews
from cvdp.components import views as componentviews
from authapp import views as authapp_views

from django.conf import settings
from django.contrib import admin
from rest_framework.routers import DefaultRouter
from django.views.generic import TemplateView, RedirectView

router = DefaultRouter()
router.register(r'contacts', groupviews.ContactAPIView, basename='contactapi')
router.register(r'cases', caseviews.CaseAPIView, basename='caseapi')

post_detail = caseviews.PostAPIView.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy',
})
post_list = caseviews.PostAPIView.as_view({
    'get': 'list',
    'post': 'create'
})
thread_detail = caseviews.CaseThreadAPIView.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})
thread_list = caseviews.CaseThreadAPIView.as_view({
    'get': 'list',
    'post': 'create'
})
    



urlpatterns = [
    path('api/', include(router.urls)),
    path('api/user/', views.UserAPIView.as_view(), name='userapi'),
    path('logout/', RedirectView.as_view(url='/accounts/logout/'), name='logout'),
    #path('api/coordinators/', views.CoordinatorAPIView.as_view(), name='coordinatorapi'),
    path('403/', views.permission_denied_view, name='forbidden'),
    #path('test/', views.static_view, name='test'),
    re_path(r"^$", RedirectView.as_view(pattern_name="cvdp:dashboard"), name='index'),
    path('profile/newcolor/', views.GenerateNewRandomColor.as_view(), name='newcolor'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('maintenance/', TemplateView.as_view(template_name='cvdp/maintenance.html'), name='maintenance'),
    re_path(r"^quickSearch/$", views.quickSearch, name='quicksearch'),
    path('search/', views.SearchAllView.as_view(), name='search'),
    path('api/search/', views.APISearchView.as_view(), name='apisearch'),
    path('reports/', reportviews.ReportsView.as_view(), name='reports'),
    path('report/', reportviews.ReportView.as_view(), name='report'),
    path('api/report/', reportviews.CustomReportAPIView.as_view({'post': 'create'}), name='report_api'),
    re_path(r"^api/case/(?P<caseid>\d+)/report/edit/$", reportviews.EditCustomReportAPIView.as_view({'post': 'create'}), name='edit_report_api'),
    path('metrics/', caseviews.CaseMetricsView.as_view(), name='metrics'),
    path('api/metrics/', caseviews.CaseMetricsAPIView.as_view(), name='metricsapi'),
    re_path(r"^cases/(?P<caseid>\d+)/report/edit/$", reportviews.EditReportView.as_view(), name='editreport'),
    re_path(r"^report/add/case/(?P<caseid>\d+)/$", reportviews.AddReportView.as_view(), name='addreport'),
    re_path(r"^report/case/(?P<caseid>\d+)/add/$", reportviews.AddCaseReportView.as_view(), name='add_case_report'),
    re_path(r"^case/(?P<caseid>\d+)/report/original/$", reportviews.OrigReportAPIView.as_view({'get': 'retrieve'}), name='origreportsapi'),
    path('inbox/', msgviews.InboxView.as_view(), name='inbox'),
    re_path(r"^inbox/thread/(?P<pk>\d+)/$", msgviews.InboxView.as_view(), name='inboxthread'),
    re_path(r"^inbox/(?P<contact>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/$", msgviews.InboxView.as_view(), name='msg_contact'),
    re_path(r"^inbox/(?P<contact>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/(?P<admin>admin)/$", msgviews.InboxView.as_view(), name='msg_groupadmin'),
    re_path(r"^inbox/(?P<contact>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/(?P<admin>admin)/bounce/(?P<bounce>\d+)/$", msgviews.InboxView.as_view(), name='msg_groupadmin_bounce'),
    re_path(r"^artifact/(?P<path>.*)/$", views.ArtifactView.as_view(), name='artifact'),
    path('api/form/submissions/', reportviews.ReportsAPIView.as_view({'get': 'list'}), name='reportsapi'),
    path('api/inbox/unread/', msgviews.UnreadMessageAPI.as_view(), name='unread'),
    re_path(r"^api/inbox/thread/(?P<pk>\d+)/$", msgviews.MessageAPIView.as_view({'get':'list', 'post': 'create'}), name='msgapi'),
    path('api/inbox/', msgviews.ThreadAPIView.as_view({'get':'list', 'post': 'create'}), name='inboxapi'),
    re_path(r"api/inbox/(?P<pk>\d+)/$", msgviews.ThreadAPIView.as_view({'get':'retrieve'}), name='inbox_thread'),
    path('api/inbox/upload/', msgviews.MessageUploadView.as_view(), name='newmsgupload'),
    re_path(r"^api/inbox/thread/(?P<pk>\d+)/upload/$", msgviews.MessageUploadView.as_view(), name='msgupload'),
    path('group/admin/', groupviews.GroupAdminView.as_view(), name='groupadmin'),
    path('api/manage/group/admin/', groupviews.GroupAdminAPIView.as_view({'get': 'list'}), name='groupadminapi'),
    re_path(r"^api/manage/group/(?P<group>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/api/$", groupviews.GroupAPIAccountView.as_view({'get': 'list', 'post': 'create'}), name='groupapikeys'),
    re_path(r"^api/manage/group/(?P<group>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/api/(?P<key>[0-9a-zA-Z]+)/$", groupviews.GroupAPIAccountView.as_view({'delete': 'destroy', 'patch':'partial_update'}), name='rmgroupapikey'),
    re_path(r"^api/manage/group/(?P<group>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/admin/$", groupviews.GroupAdminAPIView.as_view({'patch': 'partial_update', 'get': 'retrieve'}), name='groupadminapi'),
    re_path(r"^api/manage/group/admin/(?P<group>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/$", groupviews.GroupAdminAPIView.as_view({'get': 'retrieve'}), name='groupadminapi'),
    re_path(r"^groups/(?P<group>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/$", groupviews.GroupSearchView.as_view(), name='group'),
    re_path(r"^api/manage/group/(?P<group>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/perms/$", groupviews.GroupCasePermAPIView.as_view({'get': 'list', 'patch': 'partial_update'}), name='groupcaseperms'),
    #re_path(r"^groups/(?P<pk>[0-9]+)/$', groupviews.GroupSearchView.as_view(), name='group'),
    path('groups/unverified', groupviews.GroupSearchView.as_view(), name='unverified'),
    re_path(r"^groups/(?P<group>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/components/$", groupviews.GroupComponentsView.as_view(), name='group_components'),
    path('groups/', groupviews.GroupSearchView.as_view(), name='searchgroups'),
    re_path(r"^groups/(?P<group>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/?(err)?/?", groupviews.GroupSearchView.as_view(), name='searchgroups'),
    path('groups/new/', groupviews.CreateGroupView.as_view(), name='newgroup'),
    path('contact/new/', groupviews.CreateContactView.as_view(), name='newcontact'),
    re_path(r"^contact/new/(?P<pk>[0-9]+)/$", groupviews.CreateContactView.as_view(), name='newcontact'),
    re_path(r"^contact/(?P<slug>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/$", groupviews.GroupSearchView.as_view(), name='contact'),
    re_path(r"^contact/(?P<slug>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/detail/$", groupviews.ContactView.as_view(), name='contact-internal'),
    re_path(r"^api/group/(?P<group>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/$", groupviews.GroupDetailAPIView.as_view({'get': 'retrieve', 'delete': 'destroy', 'patch':'partial_update'}), name="groupdetailapi"),
    path('api/group/', groupviews.GroupDetailAPIView.as_view({'get': 'list', 'post': 'create'}), name="group_api"),
    path('api/groups/', groupviews.GroupAPIView.as_view(), name='groupapi'),
    path('api/groups/unverified/', groupviews.UnverifiedContactsAPIView.as_view({'get': 'list'}), name="unverified_api"),
    re_path(r"^api/groups/(?P<group>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/contacts/$", groupviews.ContactAssociationAPIView.as_view({'get':'list', 'post':'create'}), name='assoc_api'),
    re_path(r"^api/groups/contacts/(?P<pk>[0-9]+)/$", groupviews.ContactAssociationAPIView.as_view({'patch': 'partial_update', 'delete':'destroy'}), name='assoc_api_detail'),
    re_path(r"api/group/request/", groupviews.ContactAssociationRequestAPIView.as_view({'post': 'create'}), name="request_ca"),
    re_path(r"^api/contact/(?P<contact>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/$", groupviews.GetContactAPIView.as_view(), name='get_contact_api'),
    re_path(r"^api/contact/(?P<contact>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/activity/$", groupviews.ContactActivityAPIView.as_view({'get': 'list'}), name='contact_activityapi'),
    re_path(r"^api/group/(?P<group>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/activity/$", groupviews.ContactActivityAPIView.as_view({'get': 'list'}), name='group_activityapi'),
    re_path(r"^api/contact/activity/$", groupviews.ContactActivityAPIView.as_view({'get': 'list'}), name='contactactivityapi'),
    path('api/groups/coordinators/', groupviews.CoordTeamAPIView.as_view({'get': 'list', 'post': 'create'}), name='coord_team_api'),
    re_path(r"^api/groups/coordinators/(?P<group>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/$", groupviews.CoordTeamAPIView.as_view({'delete': 'destroy'}), name='rm_coord_team'),

    #external transfers
    
    path('api/transfers/report/', reportviews.ReportTransferAPIView.as_view({'post': 'create'}), name='transfer_reportapi'),
    path('api/case/transfers/', caseviews.CaseTransferAPIView.as_view({'get': 'list', 'post': 'create'}), name='casetransferapi'),
    re_path(r"^api/case/(?P<caseid>[0-9]+)/transfers/", caseviews.CaseTransferAPIView.as_view({'get': 'list', 'post': 'create'}), name='casetransferapi-casedetail'),
    re_path(r"^api/case/(?P<pk>[0-9]+)/transfers/$", caseviews.CaseTransferAPIView.as_view({'get': 'retrieve'}), name='casetransferapi-detail'),
    re_path(r"^api/transfers/case/(?P<caseid>[0-9]+)/artifacts/$", caseviews.ArtifactTransferAPIView.as_view({'post': 'create'}), name='transfer_artifactapi'),
    re_path(r"^api/transfers/case/(?P<caseid>[0-9]+)/vuls/$", caseviews.VulTransferAPIView.as_view({'post':'create'}), name='transfer_vulapi'),
    re_path(r"^api/transfers/case/(?P<caseid>[0-9]+)/advisory/$", caseviews.AdvisoryTransferAPIView.as_view({'post':'create'}), name='transfer_advisoryapi'),
    re_path(r"^api/transfers/case/(?P<caseid>[0-9]+)/status/$", caseviews.StatusTransferAPIView.as_view({'post':'create'}), name='transfer_statusapi'),
    re_path(r"^api/transfers/case/(?P<caseid>[0-9]+)/thread/$", caseviews.ThreadTransferAPIView.as_view({'post':'create'}), name='transfer_postapi'),
    re_path(r"^api/group/(?P<group>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/cases/$", caseviews.GroupCasesAPIView.as_view({'get': 'list'}), name='group_caseapi'),
    re_path(r"^api/contact/(?P<contact>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/cases/$", caseviews.ContactCasesAPIView.as_view({'get': 'list'}), name='contact_caseapi'),
    re_path(r"^api/contact/(?P<contact>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/cases/activity/$", caseviews.ContactActivityAPIView.as_view({'get': 'list'}), name='contact_caseactivityapi'),
    path('api/case/notifications/', caseviews.CaseNotificationAPI.as_view(), name='notifications'),
    path('api/case/metadata/', caseviews.CaseMetadataAPIView.as_view(), name='metadata'),
    re_path(r"^api/case/(?P<caseid>[0-9]+)/metadata/", caseviews.CaseMetadataAPIView.as_view(), name='metadata'),
    path('api/case/states/', caseviews.CaseStateAPIView.as_view({'get': 'list'}), name='states'),
    path('cases/', caseviews.CasesView.as_view(), name='casesearch'),
    path('case/new/', caseviews.CreateNewCaseView.as_view(), name='newcase'),
    re_path(r"^cases/(?P<caseid>[0-9]+)/?(err)?/?$", caseviews.CasesView.as_view(), name='case'),
    re_path(r"^cases/(?P<caseid>[0-9]+)/status/$", caseviews.CasesView.as_view(), name='casestatus'),
    re_path(r"^cases/(?P<caseid>[0-9]+)/table/$", caseviews.CasesView.as_view(), name='casestatusxls'),
    re_path(r"^cases/(?P<caseid>[0-9]+)/dash/$", caseviews.CasesView.as_view(), name='casedash'),
    re_path(r"^cases/(?P<caseid>[0-9]+)/csaf/$", caseviews.CasesView.as_view(), name='casecsaf'),
    re_path(r"^cases/(?P<caseid>[0-9]+)/csaf/pdf/$", caseviews.CSAFPDFView.as_view(), name='csafpdf'),
    #re_path(r"^case/(?P<caseid>[0-9]+)/$", caseviews.CaseView.as_view(), name='case'),
    re_path(r"^cases/(?P<caseid>[0-9]+)/edit/$", caseviews.EditCaseView.as_view(), name='edit_case'),
    re_path(r"^cases/(?P<caseid>[0-9]+)/advisory/$", caseviews.CasesView.as_view(), name='advisory'),
    re_path(r"^cases/(?P<caseid>[0-9]+)/advisory/preview/$", caseviews.CasesView.as_view(), name='advisorypreview'),
    re_path(r"^cases/(?P<caseid>[0-9]+)/advisory/validator/$", caseviews.CoordinatorCaseView.as_view(), name='csafvalidator'),
    re_path(r"^cases/(?P<caseid>[0-9]+)/advisory/revisions/$", caseviews.CoordinatorCaseView.as_view(), name='advisory_revisions'),
    re_path(r"^vul/(?P<pk>[0-9]+)/$", caseviews.VulRedirectView.as_view(), name='vul_redirect'),
    re_path(r"^api/case/(?P<caseid>[0-9]+)/advisory/latest/$", caseviews.AdvisoryAPIView.as_view({'get': 'retrieve', 'patch': 'partial_update'}), name='advisoryapi'),
    re_path(r"^api/case/(?P<caseid>[0-9]+)/advisory/revisions/$", caseviews.AdvisoryRevisionAPIView.as_view({'patch': 'partial_update'}), name='advisoryrevapi'),
    re_path(r"^api/case/(?P<caseid>[0-9]+)/advisory/$", caseviews.AdvisoryAPIView.as_view({'get': 'list', 'post': 'create'}), name='advisoryapi-list'),
    re_path(r"^api/case/(?P<caseid>[0-9]+)/advisory/csaf/$", caseviews.CSAFAdvisoryAPIView.as_view(), name='csafapi'),
    re_path(r"^api/case/(?P<caseid>[0-9]+)/advisory/csaf/download/$", caseviews.CSAFAdvisoryDownloadView.as_view(), name='csaf_download'),
    re_path(r"^api/case/(?P<caseid>[0-9]+)/settings/csaf/$", caseviews.CSAFSettingsAPIView.as_view({'get': 'retrieve', 'post': 'create'}), name='csafsettings'),
    re_path(r"^api/case/(?P<caseid>[0-9]+)/settings/csaf/assign_doc_id/$", caseviews.get_csaf_doc_id, name="get_csaf_doc_id"),
    path('api/advisory/upload/', caseviews.AdvisoryUploadView.as_view(), name='advisoryupload'),
    #re_path(r"^case/(?P<caseid>[0-9]+)?/post/filter/", caseviews.CasePostFilterView.as_view(), name='searchposts'),
    #re_path(r"^cases/(?P<caseid>[0-9]+)/participants/$", caseviews.ManageCaseParticipants.as_view(), name='caseparticipants'),
    re_path(r"^cases/(?P<caseid>[0-9]+)/participants/$", caseviews.CasesView.as_view(), name='caseparticipants'),
    re_path(r"^cases/(?P<caseid>[0-9]+)/vuls/$", caseviews.CasesView.as_view(), name='casevuls'),
    #re_path(r"^case/post/(?P<pk>[0-9]+)/$", caseviews.PostView.as_view(), name='post'),
    #re_path(r"^case/posts/(?P<pk>[0-9]+)/$", caseviews.ThreadPostsView.as_view(), name='posts'),
    re_path(r"^case/thread/post/diff/(?P<revision_id>[0-9]+)/$", caseviews.PostDiffView.as_view(), name='diff'),
    re_path(r"^api/case/(?P<caseid>\d+)/threads/archived/$", caseviews.ArchivedThreadView.as_view({'get': 'list'}), name='archived'),
    re_path(r"^api/case/thread/(?P<pk>\d+)/posts/$", post_list, name='postlistapi'),
    
    re_path(r"^api/case/thread/post/(?P<pk>[0-9]+)/$", post_detail, name='postapi'),
    re_path(r"^api/case/thread/post/(?P<pk>[0-9]+)/react/$", caseviews.ReactPostAPIView.as_view({'get': 'list', 'post': 'create'}), name='reactapi'),
    re_path(r"^api/case/(?P<caseid>\d+)/threads/$", thread_list, name='threadlistapi'),
    re_path(r"^api/case/thread/(?P<pk>[0-9]+)/$", thread_detail, name='threadapi'),
    re_path(r"^api/case/(?P<caseid>\d+)/threads/search/$", caseviews.SearchThreadsAPIView.as_view({'get': 'list'}), name='searchthreads'),

    re_path(r"^api/case/thread/(?P<pk>\d+)/upload/$", caseviews.UploadPostFile.as_view(), name='uploadfile'),
    re_path(r"^api/case/thread/(?P<pk>[0-9]+)/participants/$", caseviews.CaseThreadParticipantAPIView.as_view({'get': 'list', 'post':'create'}), name='thread_participant_api'),
    re_path(r"^api/case/thread/participant/(?P<pk>[0-9]+)/$", caseviews.CaseThreadParticipantAPIView.as_view({'delete':'destroy'}), name='thread_participant_api'),
    re_path(r"^api/case/(?P<caseid>\d+)/user/$", caseviews.UserCaseStateAPIView.as_view(), name='usercaseapi'),
    re_path(r"api/case/(?P<caseid>[0-9]+)/user/assignments/", caseviews.assignable_case_api),
 
    re_path(r"^api/case/(?P<caseid>\d+)/activity/$", caseviews.CaseActivityAPIView.as_view({'get': 'list'}), name='activityapi'),
    re_path(r"^api/case/activity/$", caseviews.CaseActivityAPIView.as_view({'get': 'list'}), name='allactivityapi'),
    re_path(r"^api/case/(?P<caseid>\d+)/participants/$", caseviews.CaseParticipantAPIView.as_view({'get':'list', 'post':'create'}), name='case_participant_api_list'),
    re_path(r"^api/case/participant/(?P<pk>[0-9]+)/$", caseviews.CaseParticipantAPIView.as_view({'patch': 'partial_update', 'delete': 'destroy'}), name='case_participant_api'),
    re_path(r"^api/case/(?P<caseid>\d+)/participants/summary/$", caseviews.CaseParticipantSummaryAPIView.as_view(), name='case_participant_summary_api'),
    re_path(r"^case/(?P<caseid>\d+)/participants/notify/$", caseviews.NotifyVendorsView.as_view(), name='notifyvendors'),
    re_path(r"^case/(?P<caseid>\d+)/participants/notify/all/$", caseviews.NotifyVendorsView.as_view(), name='notifyallvendors'),
    re_path(r"^api/case/(?P<caseid>[0-9]+)/vuls/$", caseviews.VulAPIView.as_view({'get': 'list', 'post':'create'}), name='vulapi'),
    re_path(r"^api/case/(?P<caseid>[0-9]+)/artifacts/$", caseviews.CaseArtifactAPIView.as_view({'get': 'list', 'post':'create'}), name='artifactapi'),
    re_path(r"^api/case/artifact/(?P<uuid>.*)/$", caseviews.CaseArtifactAPIView.as_view({'get': 'retrieve', 'patch': 'partial_update', 'delete':'destroy'}), name='artifactapi-detail'),
    re_path(r"^api/vul/(?P<pk>[0-9]+)/$", caseviews.VulAPIView.as_view({'get': 'retrieve', 'delete':'destroy', 'patch': 'partial_update'}), name='vulapi-detail'),
    re_path(r"^api/vul/(?P<pk>[0-9]+)/vex/$", caseviews.VulVEXAPIView.as_view(), name='vexapi'),
    re_path(r"^case/vul/(?P<pk>[0-9]+)/cvss/$", caseviews.ScoreVulCVSSView.as_view(), name='cvss'),
    re_path(r"^api/case/vul/(?P<pk>[0-9]+)/cvss/$", caseviews.CVSSVulView.as_view({'get':'list', 'post': 'create', 'patch': 'partial_update'}), name='cvssapi'),
    re_path(r"^api/case/vul/(?P<pk>[0-9]+)/cvss/v(?P<version>[\.0-9]+)/$", caseviews.CVSSVulView.as_view({'get': 'retrieve', 'delete':'destroy'}), name='cvss_version_api'),
    re_path(r"^api/case/vul/(?P<pk>[0-9]+)/ssvc/$", caseviews.SSVCVulView.as_view({'get': 'retrieve', 'post': 'create', 'patch': 'partial_update', 'delete': 'destroy'}), name='ssvcapi'),
    re_path(r"^api/case/(?P<caseid>\d+)/tickets/$", ticketviews.CaseTicketAPIView.as_view({'get': 'list'}), name='caseticketapi'),

    path('api/approvals/', caseviews.CaseApprovalAPIView.as_view({'get': 'list'}), name='approval_api'),
    re_path(r"^api/case/(?P<caseid>[0-9]+)/approvals/$", caseviews.CaseApprovalAPIView.as_view({'get': 'list', 'post': 'create'}), name='create_approval_api'),
    re_path(r"^api/case/approvals/(?P<pk>[0-9]+)/$", caseviews.CaseApprovalAPIView.as_view({'get': 'retrieve', 'patch': 'partial_update', 'delete':'destroy'}), name='approval_detail_api'),
    re_path(r"^manage/system/[\w+]?/?", manageviews.SystemAdminView.as_view(), name='system_admin'),
    re_path(r"^manage/csaf/[\w+]?/?", manageviews.CSAFAdminView.as_view(), name='csaf_settings'),
    path('manage/bounces/', views.TriageView.as_view(), name='email_bounces'),
    path('manage/users/', manageviews.UserAdminView.as_view(), name='user_admin'),
    path('api/manage/users/pending/', manageviews.PendingUsersAPI.as_view({'get': 'list'}), name='pendingusers'),
    path('api/manage/users/new/', manageviews.NewUsersAPIView.as_view({'get': 'list'}), name='newusers'),
    re_path(r"^api/manage/users/pending/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/$", manageviews.PendingUsersAPI.as_view({'patch': 'partial_update'}), name='pendingusers'), 
    path('manage/forms/create/', manageviews.CreateNewReportingForm.as_view(), name='create_form'),
    path('manage/forms/', manageviews.FormManagement.as_view(), name='manage_forms'),
    re_path(r"^manage/forms/(?P<pk>\d+)/design/$", manageviews.DesignReportingForm.as_view(), name='design_form'),
    #re_path(r"^manage/forms/(?P<pk>\d+)/design/question/$", manageviews.QuestionForm.as_view(), name='newquestion'),
    #re_path(r"^manage/forms/question/(?P<pk>\d+)/$", manageviews.QuestionDetail.as_view(), name='question'),
    re_path(r"^api/manage/form/(?P<pk>\d+)/$", manageviews.ReportingFormAPIView.as_view({'get': 'retrieve', 'delete': 'destroy'}), name='form_api'),
    re_path(r"^manage/forms/(?P<pk>\d+)/edit/$", manageviews.CreateNewReportingForm.as_view(), name='editform'),
    re_path(r"^api/manage/form/question/(?P<pk>\d+)/$", manageviews.QuestionAPIView.as_view({'get': 'retrieve', 'delete': 'destroy', 'patch': 'partial_update'}), name='question_api'),
    re_path(r"^api/manage/form/(?P<pk>\d+)/question/$", manageviews.QuestionAPIView.as_view({'post': 'create', 'get': 'list'}), name='question_api'),
    path('manage/cve/', manageviews.CVEServicesDashboard.as_view(), name='cve_services'),
    re_path(r"^manage/cve/(?P<pk>\d+)/$", manageviews.CVEServicesDashboard.as_view(), name='cve_services'),
    #path('manage/cve/add/', manageviews.CVEServicesAccountManagement.as_view(), name='add_cve_account'),
    re_path(r"^manage/cve/(?P<pk>\d+)/edit/$", manageviews.CVEServicesAccountManagement.as_view(), name='edit_cve_account'),
    
    path('api/manage/cve/account/', manageviews.CVEAccountAPI.as_view({'get': 'list', 'post':'create'}), name='cve_api'),
    re_path(r"^api/manage/cve/account/(?P<pk>\d+)/$", manageviews.CVEAccountAPI.as_view({'get': 'retrieve', 'patch':'update', 'delete': 'destroy'}), name='cve_api'),
    re_path(r"^api/manage/cve/reserve/$", manageviews.CVEReservationAPI.as_view({'get': 'list', 'post': 'create'}), name='cve_res_api'),
    path('api/manage/case/options/resolutions/', manageviews.ResolutionAPIView.as_view({'get': 'list', 'post': 'create'}), name='res_api'),
    re_path(r"^api/manage/case/options/resolution/(?P<pk>\d+)/$", manageviews.ResolutionAPIView.as_view({'delete': 'destroy'}), name='res_api_detail'),
    path('api/manage/csaf/profiles/', manageviews.CSAFProfilesAPIView.as_view({'get': 'list', 'post': 'create'}), name='csaf_profile_api'),
    re_path(r"^api/manage/csaf/profiles/(?P<pk>\d+)/$", manageviews.CSAFProfilesAPIView.as_view({'delete': 'destroy', 'patch': 'update', 'get': 'retrieve'})),
    path('api/user/assignments/', views.assignable_users_api),
    path('api/manage/email/templates/', manageviews.EmailTemplateAPI.as_view({'get': 'list'}), name='emailtmpl_api'),
    path('api/manage/connections/', manageviews.ConnectionAPI.as_view({'get': 'list', 'post': 'create'}), name='connection_api'),
    re_path(r"^api/manage/connection/(?P<pk>\d+)/$", manageviews.ConnectionAPI.as_view({'get': 'retrieve', 'patch': 'partial_update', 'delete':'destroy'}), name='connection_detail_api'),
    path('api/manage/autoassignment/', manageviews.AutoAssignmentAPIView.as_view({'get': 'list', 'post':'create'}), name='autoassign_api'),
    re_path(r"^api/manage/autoassignment/(?P<pk>\d+)/$", manageviews.AutoAssignmentAPIView.as_view({'delete': 'destroy', 'get': 'list', 'patch':'partial_update'}), name='autoassign_api'),
    path('api/manage/tags/', manageviews.TagAPIView.as_view({'get': 'list', 'post': 'create'}), name='tag_api'),
    re_path(r"^api/manage/tag/(?P<pk>\d+)/$", manageviews.TagAPIView.as_view({'delete': 'destroy'}), name='rm_manage_tag'),

    path('api/manage/vul/attributes/', manageviews.VulAttributesAPIView.as_view({'get': 'list', 'post': 'create'}), name='vul_attr_api'),
    re_path(r"^api/manage/vul/attributes/(?P<pk>\d+)/$", manageviews.VulAttributesAPIView.as_view({'delete': 'destroy'}), name='rm_vul_attr'),
    re_path(r"^api/case/(?P<caseid>\d+)/assign/$", caseviews.assign_case, name='assign_case'),
    re_path(r"^api/case/(?P<caseid>\d+)/unassign/$", caseviews.unassign_case, name='unassign_case'),
    path('triage/', views.TriageView.as_view(), name='triage'),
    re_path(r"^triage/calendar/?(err)?/?$", views.TriageView.as_view(), name='triage_cal'),
    path('api/triage/calendar/', manageviews.TriageCalendarMetaAPIView.as_view(), name='triage_cal'),
    path('api/triage/calendar/events/', manageviews.TriageCalendarEventAPIView.as_view({'get': 'list', 'post':'create'}), name='triage_cal_event'),
    re_path(r"^api/triage/calendar/events/(?P<pk>[0-9]+)/$", manageviews.TriageCalendarEventAPIView.as_view({'patch': 'partial_update', 'delete':'destroy'}), name='triage_cal_event_update'),
    path('api/triage/', views.TriageAPIView.as_view({'get': 'list'}), name='triageapi'),
    re_path(r"^triage/(?P<pk>[0-9]+)/$", views.TriageView.as_view(), name='triage'),
    path('api/triage/meta/', views.TriageMetaAPIView.as_view(), name='triage_meta'),
    path('api/cwe/', caseviews.CWEAPIView.as_view({'get': 'list'}), name='cweapi'),
    re_path(r"^api/group/(?P<group>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/components/$", componentviews.GroupComponentsAPIView.as_view({'get': 'list', 'post': 'create'}), name='group_components_api'),
    path('api/components/', componentviews.ComponentAPIView.as_view({'get': 'list', 'post': 'create'}), name='componentapi'),
    re_path(r"^api/component/(?P<pk>\d+)/$", componentviews.ComponentAPIView.as_view({'get': 'retrieve', 'patch': 'partial_update', 'delete': 'destroy'}), name='componentapi-detail'),
    path('components/', componentviews.ComponentView.as_view(), name='components'),
    re_path(r"^components/(?P<pk>\d+)/?(err)?/?$", componentviews.ComponentView.as_view(), name='componentdetail'),
    path('components/add/', componentviews.AddComponentView.as_view(), name='addcomponent'),
    path('api/components/upload/', componentviews.UploadSPDXFile.as_view(), name='spdxupload'),
    re_path(r"^api/components/group/(?P<group>[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/upload/", componentviews.UploadSPDXFile.as_view(), name='spdxuploadgroup'),
    path('components/update/owner/', componentviews.ChangeComponentOwnershipView.as_view(), name='change_owner'),
    re_path(r"^components/(?P<pk>\d+)/edit/$", componentviews.AddComponentView.as_view(), name='addcomponent'),
    re_path(r"^api/component/(?P<pk>\d+)/dependency/$", componentviews.DependencyAPIView.as_view({'patch':'partial_update', 'get': 'list'}), name='dependencyapi'), 
    #path('api/products/', componentviews.DependencyAPIView.as_view({'get': 'list'}), name='productapi'),
    re_path(r"^component/(?P<pk>\d+)/sbom/download/$", componentviews.DownloadSPDXFile.as_view(), name='dlsbom'),

    re_path(r"^api/case/(?P<caseid>[0-9]+)/components/$", componentviews.ComponentStatusAPIView.as_view({'get':'list', 'post':'create'}), name='statusapi'),
    re_path(r"^api/case/component/(?P<pk>[0-9]+)/status/$", componentviews.ComponentStatusAPIView.as_view({'get':'retrieve', 'delete':'destroy', 'patch': 'partial_update'}), name='statusapi-detail'),
    re_path(r"^api/case/component/(?P<pk>[0-9]+)/status/approve/$", componentviews.ApproveStatusAPIView.as_view(), name='approve-api'),
    re_path(r"^api/case/component/(?P<case_id>\d+)/status/approve/all/$", componentviews.ApproveStatusAPIView.as_view(), name='approve-all-api'),
    re_path(r"^api/case/component/(?P<pk>[0-9]+)/status/revisions/$", componentviews.ComponentStatusRevisionAPIView.as_view({'get':'list'}), name='statusrevapi-detail'),
    re_path(r"^api/components/(?P<pk>\d+)/cases/$", componentviews.CaseComponentAPIView.as_view({'get':'list'}), name='casecompapi'),
    re_path(r"^api/case/(?P<caseid>\d+)/components/status/$", componentviews.ComponentStatusTableView.as_view({'get':'list'}), name='comptableapi'),
    re_path(r"^api/component/(?P<pk>[0-9]+)/activity/$", componentviews.ComponentActionAPIView.as_view({'get':'list'}), name='compapi-activity'),
    re_path(r"^api/case/(?P<caseid>\d+)/status/transfers/$", componentviews.StatusTransfersAPIView.as_view({'get': 'list'}), name='compapi-transfers'),
    re_path(r"^api/case/status/transfer/(?P<pk>[0-9]+)/$", componentviews.StatusTransfersAPIView.as_view({'patch': 'update'}), name='compapi-merge'),
    re_path(r"^api/case/(?P<caseid>\d+)/notes/$", ticketviews.CaseNoteAPIView.as_view({'get': 'list', 'post': 'create'}), name='noteapi'),
    re_path(r"^api/ticket/(?P<pk>[0-9]+)/activity/$", ticketviews.TicketActivityAPIView.as_view({'get': 'list', 'post': 'create'}), name='ticket-activity-api'),
    re_path(r"^api/note/(?P<pk>\d+)/$", ticketviews.CaseNoteAPIView.as_view({'patch': 'update'}), name="note-detail"),
    re_path(r"^api/tickets/unassigned/$", ticketviews.UnassignedTicketAPIView.as_view({'get': 'list'}), name='triageticketapi'),
    re_path(r"^api/ticket/(?P<pk>[0-9]+)/$", ticketviews.TicketAPIView.as_view({'get': 'retrieve', 'patch': 'update'}), name='ticket-detail-api'),
    re_path(r"^api/tickets/$", ticketviews.TicketAPIView.as_view({'get': 'list'}), name='ticket-api'),
    path('tickets/', ticketviews.TicketView.as_view(), name='tickets'),
    re_path(r"^api/thread/(?P<pk>[0-9]+)/$", ticketviews.EmailAPIView.as_view({'get': 'list'}), name='threadapi'),
    re_path(r"^api/incoming/$", ticketviews.IncomingEmailAPIView.as_view(), name='emailapi'),
    re_path(r"^ticket/(?P<pk>[0-9]+)/$", ticketviews.TicketRedirectView.as_view(), name='tktredirect'),
    path('api/manage/bounce/', views.ManageEmailBounceAPIView.as_view({'get':'list'}), name='bounces'),
    re_path(r"^api/manage/bounce/(?P<pk>[0-9]+)/$", views.ManageEmailBounceAPIView.as_view({'patch': 'update'}), name='update_bounce'),
    path('api/bounce/', views.EmailBounceAPIView.as_view(), name='bounce_api'),
]


