# Generated by Django 5.1.13 on 2025-10-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_apitoken_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_api_service',
            field=models.BooleanField(default=False),
        ),
    ]
