# Generated by Django 4.2.3 on 2024-01-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0109_statusrevision_version_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
