# Generated by Django 4.2.3 on 2024-02-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0110_alter_component_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='parent',
            field=models.BooleanField(default=False, help_text='The root component'),
        ),
    ]
