# Generated by Django 4.2.3 on 2024-02-09 14:33

import cvdp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0111_component_deleted_component_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('component__name',)},
        ),
        migrations.RemoveField(
            model_name='statusrevision',
            name='justification',
        ),
        migrations.RemoveField(
            model_name='statusrevision',
            name='status',
        ),
        migrations.RemoveField(
            model_name='statusrevision',
            name='version_affected',
        ),
        migrations.RemoveField(
            model_name='statusrevision',
            name='version_name',
        ),
        migrations.RemoveField(
            model_name='statusrevision',
            name='version_type',
        ),
        migrations.RemoveField(
            model_name='statusrevision',
            name='version_value',
        ),
        migrations.AddField(
            model_name='statusrevision',
            name='version_status',
            field=models.JSONField(default=[], help_text='Array of Status Objects', validators=[cvdp.validators.JSONSchemaValidator(limit_value={'items': {'properties': {'justification': {'enum': ['Component Not Present', 'Vulnerable Code Not Present', 'Vulnerable Code not in Execute Path', 'Vulnerable Code cannot be controlled by adversary', 'Inline mitigations already exist'], 'type': ['string', 'null']}, 'status': {'enum': ['Affected', 'Not Affected', 'Fixed', 'Under Investigation', 'Unknown'], 'type': 'string'}, 'version_end_range': {'type': ['string', 'null']}, 'version_range': {'enum': ['<', '<=', None], 'type': ['string', 'null']}, 'version_type': {'enum': ['custom', 'git', 'maven', 'python', 'rpm', 'semver', None], 'type': ['string', 'null']}, 'version_value': {'type': 'string'}}, 'required': ['status', 'version_value'], 'type': 'object'}, 'type': 'array'})]),
        ),
    ]
