# Generated by Django 4.2.3 on 2024-02-09 14:35

import cvdp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0112_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusrevision',
            name='version_status',
            field=models.JSONField(default=list, help_text='Array of Status Objects', validators=[cvdp.validators.JSONSchemaValidator(limit_value={'items': {'properties': {'justification': {'enum': ['Component Not Present', 'Vulnerable Code Not Present', 'Vulnerable Code not in Execute Path', 'Vulnerable Code cannot be controlled by adversary', 'Inline mitigations already exist'], 'type': ['string', 'null']}, 'status': {'enum': ['Affected', 'Not Affected', 'Fixed', 'Under Investigation', 'Unknown'], 'type': 'string'}, 'version_end_range': {'type': ['string', 'null']}, 'version_range': {'enum': ['<', '<=', None], 'type': ['string', 'null']}, 'version_type': {'enum': ['custom', 'git', 'maven', 'python', 'rpm', 'semver', None], 'type': ['string', 'null']}, 'version_value': {'type': 'string'}}, 'required': ['status', 'version_value'], 'type': 'object'}, 'type': 'array'})]),
        ),
    ]
