# Generated by Django 4.2.7 on 2024-02-29 15:36

import cvdp.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0113_alter_statusrevision_version_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date/Time created', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Last modified.', verbose_name='Modified')),
                ('submitted_by', models.CharField(blank=True, max_length=300, null=True, verbose_name='Submitted by')),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Closed'), (3, 'In progress')], default=1, verbose_name='Status')),
                ('content', models.TextField(blank=True, help_text='The content of the ticket.', null=True, verbose_name='Task Content')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
            ],
        ),
        migrations.CreateModel(
            name='TicketThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='no_label', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='statusrevision',
            name='version_status',
            field=models.JSONField(default=list, help_text='Array of Status Objects', validators=[cvdp.validators.JSONSchemaValidator(limit_value={'items': {'properties': {'justification': {'enum': ['Component Not Present', 'Vulnerable Code Not Present', 'Vulnerable Code not in Execute Path', 'Vulnerable Code cannot be controlled by adversary', 'Inline mitigations already exist', ''], 'type': ['string', 'null']}, 'status': {'enum': ['Affected', 'Not Affected', 'Fixed', 'Under Investigation', 'Unknown'], 'type': 'string'}, 'version_end_range': {'type': ['string', 'null']}, 'version_range': {'enum': ['<', '<=', ''], 'type': ['string', 'null']}, 'version_type': {'enum': ['custom', 'git', 'maven', 'python', 'rpm', 'semver', ''], 'type': ['string', 'null']}, 'version_value': {'type': 'string'}}, 'required': ['status', 'version_value'], 'type': 'object'}, 'type': 'array'})]),
        ),
        migrations.CreateModel(
            name='TicketAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cvdp.action')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.ticket', verbose_name='Ticket')),
            ],
            bases=('cvdp.action',),
        ),
        migrations.AddField(
            model_name='ticket',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='cvdp.ticketthread'),
        ),
        migrations.CreateModel(
            name='EmailTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cvdp.ticket')),
                ('message_id', models.CharField(blank=True, help_text='email header message id', max_length=250, null=True)),
                ('references', models.JSONField(blank=True, help_text='email header references', null=True)),
                ('email_id', models.CharField(blank=True, help_text='external email reference ID, (e.g. AWS email id)', max_length=150, null=True)),
                ('email_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.emailthread')),
            ],
            bases=('cvdp.ticket',),
        ),
        migrations.CreateModel(
            name='CaseTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cvdp.ticket')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.case')),
            ],
            bases=('cvdp.ticket',),
        ),
    ]
