# Generated by Django 4.2.7 on 2024-02-29 15:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0114_emailthread_ticket_ticketthread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='ticket_gin'),
        ),
    ]
