# Generated by Django 4.2.7 on 2024-02-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0115_ticket_search_vector_ticket_ticket_gin'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''

            CREATE TRIGGER ticket_update_trigger
            BEFORE INSERT OR UPDATE of title, content
            ON cvdp_ticket
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(search_vector, 'pg_catalog.english', title, content);

            UPDATE cvdp_ticket SET search_vector = NULL;
            ''',

            reverse_sql= '''
            DROP TRIGGER IF EXISTS ticket_update_trigger
            ON cvdp_ticket;
           ''',
        ),

    ]
