# Generated by Django 4.2.7 on 2024-02-29 16:04

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0116_ticket_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
