# Generated by Django 4.2.7 on 2024-02-29 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0117_alter_ticket_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailticket',
            name='email_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='cvdp.emailthread'),
        ),
    ]
