# Generated by Django 4.2.7 on 2024-02-29 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0118_alter_emailticket_email_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.emailthread')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.emailticket')),
            ],
        ),
        migrations.AddField(
            model_name='emailthread',
            name='tickets',
            field=models.ManyToManyField(through='cvdp.ThreadTopic', to='cvdp.emailticket'),
        ),
    ]
