# Generated by Django 4.2.7 on 2024-03-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0119_threadtopic_emailthread_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailticket',
            name='parent',
            field=models.BooleanField(default=True, help_text='Set to false if this is a reply'),
        ),
    ]
