# Generated by Django 4.2.7 on 2024-03-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0120_emailticket_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailticket',
            name='sent_to',
            field=models.JSONField(blank=True, help_text='Sent To, CC', null=True),
        ),
    ]
