# Generated by Django 4.2.7 on 2024-03-01 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0121_emailticket_sent_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketthread',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cvdp.case'),
        ),
        migrations.DeleteModel(
            name='CaseTicket',
        ),
    ]
