# Generated by Django 4.2.7 on 2024-03-04 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvdp', '0122_ticketthread_case_delete_caseticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date/Time created', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Last modified.', verbose_name='Modified')),
                ('content', models.TextField(blank=True, help_text='The content of the ticket.', null=True, verbose_name='Task Content')),
                ('flagged', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.case')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
