# Generated by Django 4.2.7 on 2024-03-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0123_casenote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threadtopic',
            old_name='thread',
            new_name='ethread',
        ),
    ]
