# Generated by Django 4.2.7 on 2024-03-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0124_rename_thread_threadtopic_ethread'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketaction',
            name='comment',
            field=models.TextField(blank=True, help_text='A comment on some ticket action', null=True, verbose_name='Comment'),
        ),
    ]
