# Generated by Django 4.2.7 on 2024-03-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0125_ticketaction_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.IntegerField(choices=[(0, 'Case'), (1, 'User'), (2, 'Report'), (3, 'Message'), (4, 'Post'), (5, 'Ticket')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Closed'), (3, 'In Progress')], default=1, verbose_name='Status'),
        ),
    ]
