# Generated by Django 4.2.7 on 2024-04-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0128_ticketreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwedescriptions',
            name='cweid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cwedescriptions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
