# Generated by Django 5.0.6 on 2024-06-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0129_cwedescriptions_cweid_cwedescriptions_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseparticipant',
            name='permissions',
            field=models.JSONField(default=dict, help_text='Case access permissions set by group admin'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='permissions',
            field=models.BooleanField(default=False, help_text='Case Access permissions set by group admin. If false, all users in group have r/w on all cases.'),
        ),
    ]
