# Generated by Django 5.0.7 on 2024-08-06 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0131_vulnerability_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCSAFSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_settings', models.JSONField(default=dict, help_text='Publisher CSAF Settings')),
                ('doc_id', models.CharField(blank=True, max_length=100, null=True)),
                ('distribution_tlp', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.JSONField(default=list, help_text='Document Notes')),
                ('references', models.JSONField(default=list, help_text='Document References')),
                ('acknowledgements', models.JSONField(default=list, help_text='Document Acknowledgements')),
                ('case', models.OneToOneField(help_text='CSAF Settings', on_delete=django.db.models.deletion.CASCADE, to='cvdp.case')),
            ],
        ),
    ]
