# Generated by Django 5.0.8 on 2024-08-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0133_vulnerability_acknowledgments'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulcvss',
            name='version',
            field=models.CharField(default='3.1', max_length=20, verbose_name='CVSS Version'),
        ),
        migrations.AlterField(
            model_name='vulcvss',
            name='A',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='vulcvss',
            name='AC',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Attack Complexity'),
        ),
        migrations.AlterField(
            model_name='vulcvss',
            name='AV',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Attack Vector'),
        ),
        migrations.AlterField(
            model_name='vulcvss',
            name='C',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Confidentiality'),
        ),
        migrations.AlterField(
            model_name='vulcvss',
            name='I',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Integrity'),
        ),
        migrations.AlterField(
            model_name='vulcvss',
            name='PR',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Privileges Required'),
        ),
        migrations.AlterField(
            model_name='vulcvss',
            name='S',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='vulcvss',
            name='UI',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='User Interaction'),
        ),
    ]
