# Generated by Django 5.0.8 on 2024-09-29 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0134_vulcvss_version_alter_vulcvss_a_alter_vulcvss_ac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulcvss',
            name='vul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvss', to='cvdp.vulnerability'),
        ),
    ]
