# Generated by Django 5.0.8 on 2024-10-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0135_alter_vulcvss_vul'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwedescriptions',
            name='slice_1003',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cwedescriptions',
            name='usage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
