# Generated by Django 5.0.8 on 2024-11-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0136_cwedescriptions_slice_1003_cwedescriptions_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecsafsettings',
            name='lang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
