# Generated by Django 5.1.4 on 2025-01-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0138_csafprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='csafprofile',
            name='references',
            field=models.JSONField(default=list, help_text='Document References'),
        ),
    ]
