# Generated by Django 5.1.4 on 2025-01-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0139_csafprofile_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulcvss',
            name='metrics_json',
            field=models.JSONField(default=dict, verbose_name='CVE JSON CVSS'),
        ),
    ]
