# Generated by Django 5.1.4 on 2025-01-18 18:46

import cvdp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0140_vulcvss_metrics_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='csafprofile',
            name='distribution_tlp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='acknowledgments',
            field=models.JSONField(blank=True, default=list, null=True, validators=[cvdp.validators.JSONSchemaValidator(limit_value={'items': {'properties': {'names': {'type': 'string'}, 'organization': {'type': 'string'}}, 'required': ['names'], 'type': 'object'}, 'type': 'array'})], verbose_name='Acknowledgments'),
        ),
    ]
