# Generated by Django 5.1.4 on 2025-01-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0141_csafprofile_distribution_tlp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwedescriptions',
            name='children',
            field=models.JSONField(default=list),
        ),
    ]
