# Generated by Django 5.1.4 on 2025-03-15 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cvdp', '0143_vulnerability_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentrole',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
