# Generated by Django 5.1.4 on 2025-03-25 15:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0146_caseviewed_first_viewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VulAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField(blank=True, null=True)),
                ('last_edit', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Modified Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('vul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.vulnerability')),
            ],
        ),
    ]
