# Generated by Django 5.1.4 on 2025-03-26 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0147_vulattributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulattributes',
            name='vul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='cvdp.vulnerability'),
        ),
    ]
