# Generated by Django 5.1.4 on 2025-03-28 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0148_alter_vulattributes_vul'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseresolutionoptions',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvdp.emailtemplate'),
        ),
    ]
