# Generated by Django 5.1.4 on 2025-04-01 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0149_caseresolutionoptions_email_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vulcvss',
            old_name='vector',
            new_name='vectorString',
        ),
    ]
