# Generated by Django 5.1.4 on 2025-04-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0150_rename_vector_vulcvss_vectorstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrevision',
            name='json_content',
            field=models.JSONField(default=list, verbose_name='Slatejs JSON format'),
        ),
    ]
