# Generated by Django 5.1.4 on 2025-04-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0151_postrevision_json_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisoryrevision',
            name='json_content',
            field=models.JSONField(default=list, verbose_name='Slatejs JSON format'),
        ),
    ]
