# Generated by Django 5.1.4 on 2025-04-05 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0153_postlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlikes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
