# Generated by Django 5.1.4 on 2025-04-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0156_vulnerability_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='State name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description of transition criteria')),
                ('code', models.CharField(editable=False, max_length=100, verbose_name='Short name id used for automation')),
                ('parent', models.CharField(blank=True, max_length=100, null=True, verbose_name='This is a sub-state of parent (use code)')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Case State'),
        ),
    ]
