# Generated by Django 5.1.4 on 2025-04-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0157_casestate_case_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestate',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order of state in CVD process'),
        ),
    ]
