# Generated by Django 5.1.4 on 2025-04-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0158_casestate_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestate',
            name='color',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Info'), ('light', 'Light'), ('dark', 'Dark')], default='secondary', max_length=100, verbose_name='Badge color'),
        ),
    ]
