# Generated by Django 5.1.4 on 2025-05-07 15:48

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0161_alter_action_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adviseconnection',
            options={'verbose_name': 'VINCE-NT Connection', 'verbose_name_plural': 'VINCE-NT Connections'},
        ),
        migrations.AlterModelOptions(
            name='advisescheduledtask',
            options={'verbose_name': 'VINCE-NT Scheduled Task', 'verbose_name_plural': 'VINCE-NT Scheduled Tasks'},
        ),
        migrations.AlterModelOptions(
            name='advisetask',
            options={'verbose_name': 'VINCE-NT Task', 'verbose_name_plural': 'VINCE-NT Tasks'},
        ),
        migrations.AlterModelOptions(
            name='caseadvisory',
            options={'verbose_name_plural': 'Case Advisories'},
        ),
        migrations.AlterModelOptions(
            name='casecsafsettings',
            options={'verbose_name_plural': 'Case CSAF Settings'},
        ),
        migrations.AlterModelOptions(
            name='caseresolutionoptions',
            options={'verbose_name_plural': 'Case Resolution Options'},
        ),
        migrations.AlterModelOptions(
            name='cwedescriptions',
            options={'verbose_name': 'CWE Description', 'verbose_name_plural': 'CWE Descriptions'},
        ),
        migrations.AlterModelOptions(
            name='globalsettings',
            options={'verbose_name': 'Global Settings', 'verbose_name_plural': 'Global Settings'},
        ),
        migrations.AlterModelOptions(
            name='vulnerability',
            options={'get_latest_by': 'sequence', 'ordering': ('sequence',), 'verbose_name': 'Vulnerability', 'verbose_name_plural': 'Vulnerabilities'},
        ),
        migrations.AddField(
            model_name='caseaction',
            name='advisory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvdp.advisoryrevision'),
        ),
        migrations.AddField(
            model_name='caseaction',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvdp.postrevision'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='vul_gin'),
        ),
    ]
