# Generated by Django 5.1.4 on 2025-05-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0163_alter_vulnerability_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='support_emails',
            field=models.JSONField(default=list, help_text='Team or contact email address for organization'),
        ),
    ]
