# Generated by Django 5.1.4 on 2025-05-29 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0164_groupprofile_support_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactassociation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='cvdp.contact'),
        ),
    ]
