# Generated by Django 5.1.4 on 2025-05-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0166_grouptag'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactaction',
            name='share',
            field=models.BooleanField(default=True),
        ),
    ]
