# Generated by Django 5.1.4 on 2025-06-11 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0167_contactaction_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisescheduledtask',
            name='timeout',
            field=models.IntegerField(default=0, help_text='Number of seconds after which a job in "running" state will be considered dead and will be allowed to run again. Use 0 to disable. NOTE: This will not actually kill the job if it is still running!', validators=[django.core.validators.MinValueValidator(0, message='Only zero and positive values are valid.')]),
        ),
    ]
