# Generated by Django 5.1.4 on 2025-06-11 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0168_advisescheduledtask_timeout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VulAttributeKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, help_text='Description of attribute', max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User that added this attribute.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
