# Generated by Django 5.1.4 on 2025-06-13 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0169_vulattributekey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(help_text='The tag', max_length=50)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.component', verbose_name='Component')),
                ('user', models.ForeignKey(blank=True, help_text='User that created this tag.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
