# Generated by Django 5.1.4 on 2025-06-13 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0170_componenttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenttag',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='cvdp.component', verbose_name='Component'),
        ),
    ]
