# Generated by Django 5.1.4 on 2025-06-20 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0171_alter_componenttag_component'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Rejected'), (2, 'Approved')], default=0, verbose_name='Status')),
                ('request', models.IntegerField(choices=[(1, 'Publish Advisory'), (2, 'Publish CVE')], default=1, verbose_name='Approval Type')),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('advisory_version', models.CharField(blank=True, max_length=100, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvdp.case', verbose_name='Case')),
                ('completed_by', models.ForeignKey(blank=True, help_text='User completed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User requesting approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('vulnerability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cvdp.vulnerability', verbose_name='Vulnerability')),
            ],
        ),
    ]
