# Generated by Django 5.1.4 on 2025-07-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0172_caseapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseapproval',
            name='approval_comments',
            field=models.TextField(blank=True, help_text='Comments', null=True),
        ),
        migrations.AddField(
            model_name='caseapproval',
            name='request_comments',
            field=models.TextField(blank=True, help_text='Request Comments', null=True),
        ),
    ]
