# Generated by Django 5.1.4 on 2025-07-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0173_caseapproval_approval_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='use_custom_report',
            field=models.BooleanField(default=False, help_text='Disable Form Builder and use a custom Javascript reporting form'),
        ),
    ]
