# Generated by Django 5.1.4 on 2025-07-17 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0174_globalsettings_use_custom_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formentry',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cvdp.reportingform'),
        ),
    ]
