# Generated by Django 5.1.4 on 2025-07-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0175_alter_formentry_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='title',
            field=models.CharField(blank=True, help_text='Optional, helpful for custom reports', max_length=300, null=True),
        ),
    ]
