# Generated by Django 5.1.4 on 2025-08-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0178_rejectedassociation'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusrevision',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
