# Generated by Django 5.1.4 on 2025-08-29 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0179_statusrevision_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseaction',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Case State Transition', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvdp.casestate'),
        ),
    ]
