# Generated by Django 5.1.4 on 2025-09-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0180_caseaction_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseparticipant',
            name='pulse',
            field=models.DateTimeField(blank=True, help_text='Last time participant interacted with case.', null=True),
        ),
    ]
