# Generated by Django 5.1.4 on 2025-09-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0181_caseparticipant_pulse'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='unresponsive_pulse',
            field=models.IntegerField(default=0, help_text='Number of days'),
        ),
    ]
