# Generated by Django 5.1.4 on 2025-09-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0182_globalsettings_unresponsive_pulse'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisetask',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='A brief summary of the task performed for audit purposes'),
        ),
    ]
