# Generated by Django 5.1.4 on 2025-09-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0184_triagecalendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagecalendarevent',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='triagecalendarevent',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
