# Generated by Django 5.1.13 on 2025-10-27 19:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0186_dailyemailnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BounceEmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=320)),
                ('from_email', models.CharField(max_length=320)),
                ('bounce_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bounce_type', models.IntegerField(choices=[(0, 'Transient'), (1, 'Permanent')], default=0, verbose_name='Bounce Type')),
                ('subject', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
