# Generated by Django 5.1.13 on 2025-12-30 14:26

import cvdp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0187_bounceemailnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='support_emails',
            field=models.JSONField(blank=True, default=list, help_text='Team or contact email address for organization', null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='references',
            field=models.JSONField(default=list, validators=[cvdp.validators.JSONSchemaValidator(limit_value={'items': {'properties': {'summary': {'type': 'string'}, 'tags': {'items': {'oneOf': [{'enum': ['broken-link', 'customer-entitlement', 'exploit', 'government-resource', 'issue-tracking', 'mailing-list', 'mitigation', 'not-applicable', 'patch', 'permissions-required', 'media-coverage', 'product', 'related', 'release-notes', 'signature', 'technical-description', 'third-party-advisory', 'vendor-advisory', 'vdb-entry'], 'type': 'string'}, {'$comment': 'These values are not used as JSON property names, so there is not a need to work-around property naming limitations in some common implementations.', 'maxLength': 128, 'minLength': 2, 'pattern': '^x_.*$', 'type': 'string'}]}, 'minItems': 1, 'type': 'array', 'uniqueItems': True}, 'url': {'type': 'string'}}, 'required': ['url'], 'type': 'object'}, 'type': 'array'})], verbose_name='References'),
        ),
    ]
