# Generated by Django 5.1.13 on 2026-01-02 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cvdp', '0188_alter_groupprofile_support_emails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetag',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='cvdp.case', verbose_name='Case'),
        ),
        migrations.AlterField(
            model_name='grouptag',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='auth.group', verbose_name='Group'),
        ),
    ]
