# Generated by Django 5.1.13 on 2026-01-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0189_alter_casetag_case_alter_grouptag_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='notes',
            field=models.TextField(blank=True, help_text='Coordinator/Analyst Notes', null=True),
        ),
    ]
