# Generated by Django 5.1.13 on 2026-01-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0190_component_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='report_id',
            field=models.CharField(blank=True, help_text='Optional, but helpful for preventing duplicate entries', max_length=50, null=True),
        ),
    ]
