# Generated by Django 5.1.13 on 2026-02-02 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cvdp', '0191_formentry_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='coordinator_identity',
            field=models.CharField(blank=True, help_text='If provided, all coordinator teams will use name provided here as display to all non-coordinator accounts on the platform', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The main coordination group for this VINCE-NT instance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='problem_types',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Problem Type'),
        ),
    ]
