# Generated by Django 5.1.13 on 2026-02-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0192_globalsettings_coordinator_identity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='unresponsive_pulse',
            field=models.IntegerField(default=0, help_text='Number of days before vendor is marked as unresponsive'),
        ),
    ]
