# Generated by Django 5.1.13 on 2026-02-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0193_alter_globalsettings_unresponsive_pulse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailthread',
            name='tickets',
        ),
        migrations.DeleteModel(
            name='ThreadTopic',
        ),
    ]
