# Generated by Django 5.1.13 on 2026-02-19 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0194_remove_emailthread_tickets_delete_threadtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailticket',
            name='msg_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvdp.messagethread'),
        ),
    ]
