# Generated by Django 5.1.13 on 2026-02-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0196_ticket_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='contact_reasons',
            field=models.TextField(blank=True, help_text='Inbox message titles, separated by new line. Provide reasons why a user should use the form to contact the team', null=True),
        ),
    ]
