# Generated by Django 5.2.12 on 2026-03-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0197_globalsettings_contact_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='csafprofile',
            name='document_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
