# Generated by Django 5.2.12 on 2026-03-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0198_csafprofile_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecsafsettings',
            name='doc_id_format',
            field=models.CharField(blank=True, help_text='If doc id is generated from a format defined in a profile, set here', max_length=50, null=True),
        ),
    ]
