# Generated by Django 5.2.12 on 2026-03-30 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0199_casecsafsettings_doc_id_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentstatus',
            name='other_component',
            field=models.ForeignKey(blank=True, help_text='This is used for more complex component relationships', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_component', to='cvdp.component'),
        ),
        migrations.AddField(
            model_name='componentstatus',
            name='relationship',
            field=models.CharField(blank=True, choices=[('default_component_of', 'default component of'), ('external_component_of', 'external component of'), ('installed_on', 'installed on'), ('installed_with', 'installed with'), ('optional_component_of', 'optional component ofd')], help_text='Optional relationship from component to other component', max_length=100, null=True),
        ),
    ]
