# Generated by Django 5.2.12 on 2026-03-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdp', '0200_componentstatus_other_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentstatus',
            name='other_component_version',
            field=models.CharField(blank=True, help_text='The version number of the other component, if appropriate', max_length=100, null=True),
        ),
    ]
